name: Java Maven CI

on:
  push:
    branches: [ "main", "feature/business-logic-dev" ]
  pull_request:
    branches: [ "main", "feature-business-logic-dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write  

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v1
